version: '3.1'
services:
  db2-ibm:
      image: cwds/db2
      env_file: ./env
      ports:
          - ${DB_CMS_DB2_PORT}:${DB_CMS_DB2_PORT}
      environment:
          DB2INST1_PASSWORD: ${DB_CMS_PASSWORD}
          LICENSE: "accept"
          DB2NAME: ${DB_CMS_DB_NAME}
      command: db2start

  case-api:
      image: mzemlyanoi/case-management-api
      hostname: case-management-api
      depends_on:
        - db2-ibm
      ports:
        - ${CASE_API_PORT}:${CASE_API_PORT}
      env_file: ./env
      environment:
         SHIRO_CONFIG_PATH: ${SHIRO_CONFIG_PATH}
